### ISSUE TITLE
Add support for .button-group

### ISSUE THREAD

**Issue by ashenden** [ashenden/canvas#1]

**Comment by ashenden** [comment]
@mlunoe added support in for .button-group.  Works the same as in Bootstrap, except replace .btn with .button.  You can even use the JS to toggle states as seen here (http://getbootstrap.com/javascript/#buttons).

**Comment by mlunoe** [comment]
@ashenden Ok, thanks. I already see button groups in our latest release. Do you mean you added selected state?
