### ISSUE TITLE
Add support for .menu

### ISSUE THREAD

**Issue by ashenden** [ashenden/canvas#3]

**Comment by ashenden** [comment]
@mlunoe support has been added for dropdown menus.  Follow the Bootstrap convention.  I have really nice docs for this, but still need to publish stat versions.

**Comment by mlunoe** [comment]
Do you mean dropdown menu's? Could you create pull requests where you refer to the issue, so it is easier to see which commits relates which issues?

**Comment by ashenden** [comment]
Yes, dropdown menus and dropdown-toggles now exist.

Not sure I follow what you're looking for.  Let's connect on it in the AM.
